mex Mex_FillingInvisibleDetailC.cpp ...
    -I'F:\Program Files (x86)\OpenCV 2.4.3\opencv\build\include' ...
    -I'F:\Program Files (x86)\OpenCV 2.4.3\opencv\build\include\opencv' ...
    -I'F:\Program Files (x86)\OpenCV 2.4.3\opencv\build\include\opencv2' ...
    -L'F:\Program Files (x86)\OpenCV 2.4.3\opencv\build\x64\vc10\lib' ...
    -l'opencv_core243'...
   II_AuxiliaryFunctions.cpp II_BoundaryBlending.cpp II_ImageInpainting.cpp II_PoissonEditing.cpp linsys.cpp
    
    
